common: &common
  reconnect: true
  adapter: mysql2
  username: root
  password:
  <% if File.exist?('/tmp/mysql.sock') %>
  socket: /tmp/mysql.sock
  <% end %>

#  encoding: utf8

development: &development
  adapter: mysql2
  username: root
  password:
  <% if File.exist?('/tmp/mysql.sock') %>
  socket: /tmp/mysql.sock
  <% end %>
  database: blackline_development<%= ENV['DATABASE_SUFFIX'] %>

test: &test
  adapter: mysql2
  username: root
  password:
  <% if File.exist?('/tmp/mysql.sock') %>
  socket: /tmp/mysql.sock
  <% end %> 
  database: blackline_test<%= ENV['DATABASE_SUFFIX'] %><%= ENV['TEST_ENV_NUMBER'] %>

staging:
  reconnect: true
  adapter:  mysql2
  database: blackline_staging
  username: blackline
  password: blackline
  host: blackline-staging.cwydehrtifse.us-west-2.rds.amazonaws.com

production:
  <<: *common
  database: blackline_production<%= ENV['DATABASE_SUFFIX'] %>
